steps:
  - uses: actions/checkout@v4
  - uses: actions/setup-node@v4
    with:
      node-version: 20

  - name: Install dependencies & Build
    run: |
      yarn install
      yarn build

  - name: Publish to GitHub Packages
    env:
      PAT_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
    run: npm publish
